# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Verify_Password', models.CharField(max_length=255)),
                ('Fname', models.CharField(max_length=255)),
                ('Lname', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Availability', models.BooleanField(default=False)),
                ('Slot_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReserveParking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('Time_in', models.TimeField()),
                ('Date_in', models.DateField()),
                ('Slot_no', models.IntegerField()),
                ('Plate_no', models.CharField(max_length=7, unique=True)),
                ('Type_of_Vehicle', models.CharField(max_length=255)),
            ],
        ),
    ]
