# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Contactno',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
