# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_account_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveparking',
            name='Plate_no',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
