# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20170922_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveparking',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Account'),
        ),
    ]
