# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_auto_20170928_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveparking',
            name='Paid',
            field=models.BooleanField(default=False),
        ),
    ]
