# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_remove_transactionhistory_reserve_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='Reserve_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Project.ReserveParking'),
            preserve_default=False,
        ),
    ]
