# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0018_auto_20171001_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='Fname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='Lname',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutticket',
            name='DateTime_out',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 13, 15, 4, 560952)),
        ),
        migrations.AlterField(
            model_name='reservationfee',
            name='DateTime_paid',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 13, 15, 4, 561947)),
        ),
        migrations.AlterField(
            model_name='reserveparking',
            name='DateTimeReservation',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 13, 15, 4, 559946)),
        ),
    ]
