# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 05:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0023_auto_20171004_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='Receipt_id',
        ),
        migrations.AlterField(
            model_name='checkoutticket',
            name='DateTime_out',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 13, 27, 8, 711577)),
        ),
        migrations.AlterField(
            model_name='reservationfee',
            name='DateTime_paid',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 13, 27, 8, 712580)),
        ),
        migrations.AlterField(
            model_name='reserveparking',
            name='DateTimeReservation',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 13, 27, 8, 711577)),
        ),
    ]
